### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by baoprovip1** [pwned4ever/Od1n#1]
I install 0D1N via trollstore but every time i try jailbreak my phone will panic ( ip7plus 15.7.6 )

**Comment by pwned4ever** [comment]
Try with the latest version

Sent from my iPhone

On Feb 9, 2024, at 9:56 PM, baoprovip1 ***@***.***> wrote:

﻿

I install 0D1N via trollstore but every time i try jailbreak my phone will panic ( ip7plus 15.7.6 )
