### ISSUE TITLE
Is this an environment without Troll Store?

### ISSUE THREAD

**Issue by villager1314** [pwned4ever/Od1n#2]
I don't know if I still have the ability to continue testing, but I happen to have a iOS 15.8 tablet on hand

**Comment by pwned4ever** [comment]
Wdym is this an environment without trollstore? If your asking if you need trollstore to run this jailbreak. Then your answer is no, you don't need trollstore to run this application. It will Jailbreak your device without the need of trollstore installation, etc

Sent from my iPhone

On Feb 12, 2024, at 6:48 AM, villager1314 ***@***.***> wrote:

﻿

I don't know if I still have the ability to continue testing, but I happen to have a iOS 15.8 tablet on hand

**Comment by villager1314** [comment]
Does it need to jailbreak rootful or rootless first?

**Comment by villager1314** [comment]
If these presets are not needed, I believe this must be a great initiative

**Comment by pwned4ever** [comment]
It's a rootless jailbreak. Which you need to remove all traces of palera1n first before using this. You do not use palera1n with this Jailbreak. It's a stand-alone jailbreak to be used by itself. Not along side any other jailbreak out

Sent from my iPhone

On Feb 13, 2024, at 8:12 PM, villager1314 ***@***.***> wrote:

﻿

Does it need to jailbreak rootful or rootless first?
